        <meta charset="utf-8">
		<meta name="description" content="A Sorrowful Fashion Store For Men" />
		<meta name="keywords" content="HTML5, CSS, PHP, MySQL, fashion" />
		<meta name="author" content="The most average men on the planet"  />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"  />
		<link href="https://fonts.googleapis.com/css?family=Karma" rel="stylesheet"  />
        <link href="styles/style.css" rel="stylesheet"  />
        <title><?php echo $page_title; ?></title>