        <header>
            <nav class="navbar grid_layout">
                    <a href="#">MAYBE</a>
                    <ul class="nav_menu">
                        <li class="navbar_item"><a href="index.php">Home</a></li>
                        <li class="navbar_item"><a href="product.php">Products</a></li>
                        <li class="navbar_item"><a href="payment.php">Payment Form</a></li>
                        <li class="navbar_item"><a href="about.php">About Us</a></li>
						<li class="navbar_item"><a href="enhancements.php">Enhancements_1</a></li>
						<li class="navbar_item"><a href="enhancements2.php">Enhancements_2</a></li>
						<li class="navbar_item"><a href="manager.php">Manager</a></li>
                    </ul>
            </nav>
        </header>